import Vue from 'vue'
import { Popup, Form, Field, Picker, Dialog, ActionSheet, Rate, Lazyload, DatetimePicker, Icon, Swipe, SwipeItem, Grid, GridItem, Button, Search, Tabbar, TabbarItem, NavBar, Toast } from 'vant'

Vue.use(Toast)
Vue.use(Rate)
Vue.use(Lazyload)
Vue.use(Dialog)
Vue.use(Form)
Vue.use(Popup)
Vue.use(Field)
Vue.use(ActionSheet)
Vue.use(DatetimePicker)
Vue.use(Picker)
Vue.use(Icon)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Button)
Vue.use(Search)
